import { describe, expect, it, vi } from "vitest"
import { buildCandidateTrieForTest } from "../replace-links/__tests__/test-helpers"
import { DEFAULT_SETTINGS } from "../settings/settings-info"

class MockTFile {
    path: string

    constructor(path: string) {
        this.path = path
    }
}

vi.mock("obsidian", () => ({
    App: class {},
    Editor: class {},
    getFrontMatterInfo: () => ({ contentStart: 0 }),
    MarkdownView: class {},
    Notice: class {},
    parseFrontMatterAliases: () => [],
    Plugin: class {
        app: unknown

        constructor(app: unknown) {
            this.app = app
        }
    },
    PluginSettingTab: class {},
    request: async () => ({}),
    Setting: class {
        setName() { return this }
        setDesc() { return this }
        setHeading() { return this }
        addToggle() { return this }
        addTextArea() { return this }
    },
    TFile: MockTFile,
}))

describe("AutomaticLinkerPlugin link generator", () => {
    it.each([
        { name: "base-directory file", path: "pages/Topic", body: "Topic", baseDir: "pages", aliases: [], duplicate: false },
        { name: "base-directory file with a root duplicate", path: "pages/Topic", body: "pages/Topic", baseDir: "pages", aliases: [], duplicate: true },
        { name: "case-insensitive root file", path: "TypeScript", body: "typescript", baseDir: undefined, aliases: [], duplicate: false },
        { name: "base-directory alias", path: "pages/Topic", body: "subject", baseDir: "pages", aliases: ["subject"], duplicate: true },
        { name: "alias equal to the short path", path: "pages/Topic", body: "Topic", baseDir: "pages", aliases: ["Topic"], duplicate: false },
    ])("uses the canonical target for a $name", async ({ path, body, baseDir, aliases, duplicate }) => {
        const { default: AutomaticLinkerPlugin } = await import("../main")
        const files = [{ path, aliases }]
        if (duplicate) files.push({ path: "Topic", aliases: [] })
        const { candidateMap, trie } = buildCandidateTrieForTest({
            files,
            settings: { scoped: false, baseDir, ignoreCase: true },
        })
        const targetFile = new MockTFile(`${path}.md`)
        const rootFile = new MockTFile("Topic.md")
        const app = {
            fileManager: {
                generateMarkdownLink: vi.fn((file: MockTFile, _sourcePath: string, _subpath: string, alias: string) => {
                    const displayText = alias || file.path.slice(0, -3).split("/").pop()
                    return `[${displayText}](${file.path})`
                }),
            },
            vault: {
                getAbstractFileByPath: vi.fn((filePath: string) => {
                    if (filePath === targetFile.path) return targetFile
                    if (duplicate && filePath === rootFile.path) return rootFile
                    return null
                }),
                getConfig: vi.fn(() => baseDir),
            },
        }
        const plugin = new AutomaticLinkerPlugin(app as never, {} as never)
        plugin.settings = {
            ...DEFAULT_SETTINGS,
            ignoreCase: true,
            respectNewFileFolderPath: !!baseDir,
        }
        ;(plugin as unknown as { trie: typeof trie }).trie = trie
        ;(plugin as unknown as { candidateMap: typeof candidateMap }).candidateMap = candidateMap

        expect(plugin.modifyLinks(body, "current-file.md")).toBe(`[${body}](${path}.md)`)
        expect(app.fileManager.generateMarkdownLink).toHaveBeenCalledWith(targetFile, "current-file.md", "", expect.any(String))
    })

    it("escapes alias separators generated by Obsidian inside markdown tables", async () => {
        const { default: AutomaticLinkerPlugin } = await import("../main")
        const settings = {
            scoped: false,
            baseDir: undefined,
            ignoreCase: true,
        }
        const { candidateMap, trie } = buildCandidateTrieForTest({
            files: [{ path: "notes/foo", aliases: ["bar"] }],
            settings,
        })
        const targetFile = new MockTFile("notes/foo.md")
        const app = {
            fileManager: {
                generateMarkdownLink: vi.fn(() => "[[notes/foo|bar]]"),
            },
            vault: {
                getAbstractFileByPath: vi.fn((path: string) => {
                    if (path === "notes/foo.md") return targetFile
                    return null
                }),
                getConfig: vi.fn(),
            },
        }
        const plugin = new AutomaticLinkerPlugin(app as never, {} as never)
        plugin.settings = {
            ...DEFAULT_SETTINGS,
            formatGitHubURLs: false,
            formatJiraURLs: false,
            replaceUrlWithTitle: false,
            respectNewFileFolderPath: false,
        }
        ;(plugin as unknown as { trie: typeof trie }).trie = trie
        ;(plugin as unknown as { candidateMap: typeof candidateMap }).candidateMap = candidateMap

        const result = plugin.modifyLinks("| bar | x |\n| --- | --- |\n", "current-file.md")

        expect(result).toBe("| [[notes/foo\\|bar]] | x |\n| --- | --- |\n")
    })

    it("keeps selection formatting to link replacement only", async () => {
        const { default: AutomaticLinkerPlugin } = await import("../main")
        const settings = {
            scoped: false,
            baseDir: undefined,
            ignoreCase: true,
        }
        const { candidateMap, trie } = buildCandidateTrieForTest({
            files: [{ path: "notes/TypeScript" }],
            settings,
        })
        const replaceSelection = vi.fn()
        const app = {
            metadataCache: { getFileCache: () => ({ frontmatter: {} }) },
            workspace: {
                getActiveFile: vi.fn(() => ({ path: "current-file.md" })),
                activeEditor: {
                    editor: {
                        getValue: vi.fn(() => "TypeScript https://github.com/openai/openai/issues/1"),
                        getSelection: vi.fn(() => "TypeScript https://github.com/openai/openai/issues/1"),
                        getCursor: vi.fn(() => ({ line: 0, ch: 0 })),
                        posToOffset: vi.fn(() => 0),
                        replaceSelection,
                    },
                },
            },
            vault: {
                getConfig: vi.fn(() => "pages"),
                getAbstractFileByPath: vi.fn((path: string) => {
                    if (path === "notes/TypeScript.md") return { path: "notes/TypeScript.md" }
                    return null
                }),
            },
            fileManager: {
                generateMarkdownLink: vi.fn(() => "[[notes/TypeScript|TypeScript]]"),
            },
        }
        const plugin = new AutomaticLinkerPlugin(app as never, {} as never)
        plugin.settings = {
            ...DEFAULT_SETTINGS,
            formatGitHubURLs: true,
            formatJiraURLs: true,
            formatLinearURLs: true,
            replaceUrlWithTitle: true,
            respectNewFileFolderPath: true,
        }
        ;(plugin as unknown as { trie: typeof trie }).trie = trie
        ;(plugin as unknown as { candidateMap: typeof candidateMap }).candidateMap = candidateMap

        await plugin.mofifyLinksSelection()

        expect(replaceSelection).toHaveBeenCalledWith(
            "[[notes/TypeScript|TypeScript]] https://github.com/openai/openai/issues/1",
        )
    })
})
